test:
  host: 'merb.test.local'
  keyspace: 'merb_keyspace_test'

development:
  host: 'merb.development.local'
  keyspace: 'merb_keyspace_dev'

production:
  host: 'merb.prod'
  keyspace: 'merb_keyspace_prod'